version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: food-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: food-back
    image: ${BACKEND_IMAGE}
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    command: sh -c "sleep 5 && ./up.sh"
    restart: always

  frontend:
    container_name: food-front
    image: ${FRONTEND_IMAGE}
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    container_name: food-gateway
    image: nginx:1.19.3
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    ports:
      - 8080:80
    restart: always
